### ISSUE TITLE
Can I instantiate more than one device-mqtt containers in the same docker-compose?

### ISSUE THREAD

**Issue by stlaperriere** [edgexfoundry/device-mqtt-go#270]
Hi all,

I'm currently working on a project where I have two types of devices (type A and type B) that will send some data asynchronously over MQTT to an EdgeX deployment. Both types of device publish to their own topic on the _same_ broker:

* /data/topicA -- for device type A
* /data/topicB -- for device type B

I would like to deploy one device-mqtt container for each type of device, to loosen the coupling. My docker-compose file has the following: 

```yml
# TYPE A
  device-mqtt-type-A:
    image: edgexfoundry/docker-device-mqtt-go:1.0.0
    ports:
      - "49999:49999"
    container_name: edgex-device-mqtt-type-A
    hostname: edgex-device-mqtt-type-A
    networks:
      - edgex
    volumes:
      - ../edgex-device-drivers/device-mqtt-type-A:/custom-config
    environment:
      <<: *common-variables
      Service_Host: edgex-device-mqtt-type-A
    entrypoint:
      - /device-mqtt
      - --registry=consul://edgex-core-consul:8500
      - --confdir=/custom-config
    depends_on:
      - consul
      - data
      - metadata

# TYPE B
  device-mqtt-type-B:
    image: edgexfoundry/docker-device-mqtt-go:1.0.0
    ports:
      - "49998:49998" # I changed the port here to avoid conflicts
    container_name: edgex-device-mqtt-type-B
    hostname: edgex-device-mqtt-type-B
    networks:
      - edgex
    volumes:
      - ../edgex-device-drivers/device-mqtt-type-B:/custom-config
    environment:
      <<: *common-variables
      Service_Host: edgex-device-mqtt-type-B
    entrypoint:
      - /device-mqtt
      - --registry=consul://edgex-core-consul:8500
      - --confdir=/custom-config
    depends_on:
      - consul
      - data
      - metadata
```

There seems to be some conflicts with the two containers. When I `docker-compose up`, the two device-mqtt containers start up, but after a few seconds, the container B catches an error and crashes. Here is the error message:

```
panic: start incoming data Listener failed, please check MQTT broker settings are correct, Connection lost before Subscribe completed
```

I'm not sure what to look for... Both my devices are connected to the HiveMQ public broker using port 1883, so everything looks pretty standard to me. Here are some exerpts  from the `configuration.toml` files for both containers:

Device type A:
```toml
# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "broker.hivemq.com"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopic = "/data/topicA"
ResponseSchema = "tcp"
ResponseHost = "broker.hivemq.com"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "ResponseTopic"
```

Device type B:
```toml
# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "broker.hivemq.com"
IncomingPort = "1883"
IncomingUser = ""
IncomingPassword = ""
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopic = "/data/topicB"
ResponseSchema = "tcp"
ResponseHost = "broker.hivemq.com"
ResponsePort = "1883"
ResponseUser = ""
ResponsePassword = ""
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "ResponseTopic"
```

I guess my first question is: can two device-mqtt containers coexist within a same deployment? If so, does anyone have any idea what I'm doing wrong?

Thanks,

Sam

**Comment by lenny-intel** [comment]
Yes, just need some more configuration.

- Add `SERVICE_PORT: "49998"` to environment section so it service on the port you are exposing
- Add `EDGEX_INSTANCE_NAME: "device-mqtt-type-B"` to environment section so they don't share config and registration in Consul. This is probably causing your issue since once first config is in Consul the second one will ignore local config and just pull from Consul.
- Make sure to do clean start by removing stopped containers and volumes so Consul and DB are clear and start fresh.

**Comment by stlaperriere** [comment]
Thanks for the quick reply.

I edited the `device-mqtt-type-b` section in my docker-compose file like you said:

```yml
# TYPE B
  device-mqtt-type-B:
    image: edgexfoundry/docker-device-mqtt-go:1.0.0
    ports:
      - "49998:49998" 
    container_name: edgex-device-mqtt-type-B
    hostname: edgex-device-mqtt-type-B
    networks:
      - edgex
    volumes:
      - ../edgex-device-drivers/device-mqtt-type-B:/custom-config
    environment:
      <<: *common-variables
      Service_Host: edgex-device-mqtt-type-B
      SERVICE_PORT: "49998" # Added this
      EDGEX_INSTANCE_NAME: "edgex-device-mqtt-traverse-pieton" # Added this
    entrypoint:
      - /device-mqtt
      - --registry=consul://edgex-core-consul:8500
      - --confdir=/custom-config
    depends_on:
      - consul
      - data
      - metadata
```

After that, I removed all my containers and deleted the volumes, etc. Then I restarted everything using `docker-compose up` and I got another error. The device-mqtt-type-B still crashes, with the following message:

```
error loading config file: could not register service with Registry: unable to register service with consul: Service information not set
```
